---
  # Deploy Nautobot to the server
- name: Create Nautobot user group
  ansible.builtin.group:
    name: "{{ nautobot_group }}"

- name: Create Nautobot user and home directory
  ansible.builtin.user:
    name: "{{ nautobot_user }}"
    group: "{{ nautobot_group }}"
    shell: '/bin/bash'
    system: True
    home: "{{ nautobot_root }}"

- name: Set NAUTOBOT_ROOT in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ nautobot_root }}/.bashrc"
    line: "export NAUTOBOT_ROOT={{ nautobot_root }}"

- name: Set auto activate virtualenv in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ nautobot_root }}/.bashrc"
    line: "source {{ nautobot_virtualenv_path }}/bin/activate"

- name: Check Nautobot virtualenv with default packages
  ansible.builtin.pip:
    name: "{{ nautobot_virtualenv_python_modules }}"
    state: latest
    virtualenv: "{{ nautobot_virtualenv_path }}"
    virtualenv_command: "{{ nautobot_python_binary }} -m venv"
  become: true
  become_user: "{{ nautobot_user }}"
  retries: 2
  register: nautobot_virtualenv_setup
  until: nautobot_virtualenv_setup is succeeded

- name: Check Nautobot in virtualenv # Must be after initial because pip must be upgraded
  ansible.builtin.pip:
    name: "nautobot"
    state: "{{ 'latest' if nautobot_keep_updated else 'present' }}"
    virtualenv: "{{ nautobot_virtualenv_path }}"
    virtualenv_command: "{{ nautobot_python_binary }} -m venv"
  become: true
  become_user: "{{ nautobot_user }}"
  retries: 2
  register: nautobot_virtualenv_install
  until: nautobot_virtualenv_install is succeeded

- name: Check Nautobot python deps in virtualenv # Must be after initial because pip must be upgraded
  ansible.builtin.pip:
    name: "{{ nautobot_python_deps }}"
    state: "{{ 'latest' if nautobot_python_deps_updated else 'present' }}"
    virtualenv: "{{ nautobot_virtualenv_path }}"
    virtualenv_command: "{{ nautobot_python_binary }} -m venv"
  become: true
  become_user: "{{ nautobot_user }}"
  retries: 2
  register: nautobot_virtualenv_install_python_deps
  until: nautobot_virtualenv_install_python_deps is succeeded
  environment:
        http_proxy: "{{ http_proxy if defined else '' }}"
        https_proxy: "{{ https_proxy if defined else '' }}"

- name: Copy venv exec to execute command from within venv (so nautobot-server can be executed)
  ansible.builtin.template:
    src: venv_exec.j2
    dest: "{{ nautobot_virtualenv_path }}/exec"
    owner: "{{ nautobot_user }}"
    group: "{{ nautobot_group }}"
    mode: 0755
  become: True

- name: Check if correct installed
  command: "{{ nautobot_virtualenv_path }}/exec nautobot-server --version"
  environment:
    NAUTOBOT_ROOT: "{{ nautobot_root }}"
  become: yes
  become_user: "{{ nautobot_user }}"
  register: nautobot_version
