- name: Install required packages from list
  apt:
    name: "{{ nautobot_apt_packages | flatten }}"
    state: present
    cache_valid_time: 3600
    update_cache: true
  vars:
    nautobot_apt_packages:
      - "{{ nautobot_python_packages }}"
      - "{{ nautobot_packages }}"
      - "{{ nautobot_ldap_packages if nautobot_ldap_enabled else [] }}"
      - "{{ 'acl' if ('SUDO_USER' in ansible_env and ansible_env.SUDO_USER != 'root') else [] }}"
